services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=${NODERED_TZ:-Europe/Amsterdam}
      - NODE_RED_USERNAME=${NODE_RED_USER:-admin}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD:-password}
    ports:
      - ${NODERED_PORT:-1880}:1880
    volumes:
      - ./node-red:/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0